FROM node:20-alpine AS Builder
WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile --ignore-scripts
RUN  yarn nx build api


FROM node:20-alpine AS Service
WORKDIR /app/
COPY --from=Builder /app/node_modules ./node_modules
COPY --from=Builder /app/package.json ./package.json
COPY --from=Builder /app/dist ./dist
CMD ["yarn", "node", "/app/dist/apps/api/main.js"]